#!/usr/bin/env python3
"""Regenerate TRAILS_SUMMARY.md and TOPO_SUMMARY.md from the baked GeoJSON.

Run after the bake scripts so the docs always reflect the current data /
bounding box. Invoked automatically by `make data`.
"""
import json
import math
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from overture_common import PUBLIC, RELEASE, REPO, load_bbox  # noqa: E402

MINERAL_KING_TRAILS = {
    "Black Rock Pass Trail", "Cliff Creek Trail", "Crystal Lake Trail",
    "Eagle Lake Trail", "Farewell Gap - Franklin Lakes Trail",
    "Franklin Pass Trail", "Big Five Lakes Trail", "Upper Big Five Lakes Trail",
    "Lost Canyon Trail", "Monarch Lakes Trail", "Mosquito Lakes Trail",
    "Soda Creek Trail", "Timber Gap Trail", "Timber Gap Cliff Creek Trail",
    "White Chief Trail",
}


def load(name):
    return json.load(open(os.path.join(PUBLIC, name)))["features"]


def line_km(coords):
    R = 6371.0
    total = 0.0
    for (lo1, la1), (lo2, la2) in zip(coords, coords[1:]):
        p1, p2 = math.radians(la1), math.radians(la2)
        a = (math.sin(math.radians(la2 - la1) / 2) ** 2
             + math.cos(p1) * math.cos(p2)
             * math.sin(math.radians(lo2 - lo1) / 2) ** 2)
        total += 2 * R * math.asin(math.sqrt(a))
    return total


def geom_coords(geom):
    # Trails are now LineString Z ([lon, lat, elevation]); keep only lon/lat so
    # the planar length math below ignores the third ordinate.
    if geom["type"] == "LineString":
        return [c[:2] for c in geom["coordinates"]]
    if geom["type"] == "MultiLineString":
        return [c[:2] for part in geom["coordinates"] for c in part]
    return []


def bbox_line(b):
    return (f"lon `{b['west']} … {b['east']}`, lat `{b['south']} … {b['north']}`")


def write_trails(b):
    feats = load("trails.geojson")
    names = defaultdict(lambda: {"segments": 0, "km": 0.0, "classes": set()})
    classes = defaultdict(int)
    for f in feats:
        p = f["properties"]
        classes[p.get("class")] += 1
        v = names[p["name"]]
        v["segments"] += 1
        v["km"] += line_km(geom_coords(f["geometry"]))
        v["classes"].add(p.get("class"))

    total_km = round(sum(v["km"] for v in names.values()), 1)
    cls_line = " · ".join(f"`{c}` {n}" for c, n in
                          sorted(classes.items(), key=lambda x: -x[1]))
    longest = sorted(names.items(), key=lambda kv: -kv[1]["km"])[:10]
    mk = sorted(n for n in names if n in MINERAL_KING_TRAILS)

    lines = []
    lines.append("# Trails Summary\n")
    lines.append("> Generated by `scripts/write_summaries.py` — do not edit by "
                 "hand; re-run `make data` after changing the bounding box.\n")
    lines.append("The map overlays a baked trail layer (`public/trails.geojson`) "
                 "rendered as named lines with along-line labels and a toggle. "
                 "Trails are ingested as GeoParquet, split into <=1 km pieces, and "
                 "densified to LineString Z (a DEM elevation sample ~every 10 m).\n")
    lines.append("## Source\n")
    lines.append(f"- **Dataset:** [Overture Maps](https://overturemaps.org/) — "
                 "transportation theme, `segment` type")
    lines.append(f"- **Release:** `{RELEASE}`")
    lines.append("- **Derived from:** OpenStreetMap (ODbL — © Overture Maps / "
                 "OpenStreetMap contributors)")
    lines.append(f"- **Project bounding box:** {bbox_line(b)}")
    lines.append("- **Filter:** `subtype = road` and `class ∈ {path, footway, "
                 "track, steps, bridleway, pedestrian}` with a non-null name\n")
    lines.append("## Statistics\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Total pieces (<=1 km) | {len(feats)} |")
    lines.append(f"| Distinct named trails | {len(names)} |")
    lines.append(f"| Combined length (within bbox) | ~{total_km} km |\n")
    lines.append(f"**Segments by class:** {cls_line}\n")
    lines.append("> Lengths are summed per name and clipped to the bounding box, "
                 "so routes continuing beyond it are partial.\n")
    lines.append("## Featured long routes\n")
    lines.append("| Trail | Length (km) |")
    lines.append("|---|---:|")
    for name, v in longest:
        lines.append(f"| {name} | {round(v['km'], 1)} |")
    lines.append("")
    if mk:
        lines.append("## Mineral King valley trails\n")
        for n in mk:
            lines.append(f"- {n}")
        lines.append("")
    lines.append(f"## All distinct trail names ({len(names)})\n")
    lines.append("*Segs* = segments; *km* = summed length within the bbox.\n")
    lines.append("| Trail | Segs | km | Class |")
    lines.append("|---|---:|---:|---|")
    for name in sorted(names, key=lambda s: s.lower()):
        v = names[name]
        lines.append(f"| {name} | {v['segments']} | {round(v['km'], 1)} | "
                     f"{', '.join(sorted(c for c in v['classes'] if c))} |")
    lines.append("")
    open(os.path.join(REPO, "TRAILS_SUMMARY.md"), "w").write("\n".join(lines))
    print("  wrote TRAILS_SUMMARY.md")


def elev_rows(items):
    out = []
    for name, elev in items:
        if elev is None:
            out.append(f"| {name} | — | — |")
        else:
            out.append(f"| {name} | {elev:,} | {round(elev * 3.28084):,} |")
    return out


def write_topo(b):
    pts = load("topo-points.geojson")
    peaks = sorted([(f["properties"]["name"], f["properties"].get("elevation"))
                    for f in pts if f["properties"]["kind"] == "peak"],
                   key=lambda x: (-(x[1] or 0), x[0]))
    passes = sorted([(f["properties"]["name"], f["properties"].get("elevation"))
                     for f in pts if f["properties"]["kind"] == "pass"],
                    key=lambda x: (-(x[1] or 0), x[0]))
    lakes = sorted({f["properties"]["name"] for f in load("lakes.geojson")})
    rivers = sorted({f["properties"]["name"] for f in load("rivers.geojson")})

    lines = []
    lines.append("# Topographic Features Summary\n")
    lines.append("> Generated by `scripts/write_summaries.py` — do not edit by "
                 "hand; re-run `make data` after changing the bounding box.\n")
    lines.append("Named topographic features baked from Overture into `public/`: "
                 "`topo-points.geojson` (peaks + passes), `lakes.geojson` "
                 "(polygons), `lakes-points.geojson` (lake center-point labels), "
                 "`rivers.geojson` (lines).\n")
    lines.append("## Source\n")
    lines.append("- **Dataset:** [Overture Maps](https://overturemaps.org/) — "
                 "base theme (`land` for peaks/passes, `water` for lakes/rivers)")
    lines.append(f"- **Release:** `{RELEASE}`")
    lines.append("- **License:** ODbL — © Overture Maps / OpenStreetMap "
                 "contributors")
    lines.append(f"- **Project bounding box:** {bbox_line(b)}\n")
    lines.append("## Counts\n")
    lines.append("| Feature | Named in extract |")
    lines.append("|---|---:|")
    lines.append(f"| Peaks | {len(peaks)} |")
    lines.append(f"| Passes (saddles) | {len(passes)} |")
    lines.append(f"| Lakes | {len(lakes)} |")
    lines.append(f"| Rivers (named line features) | {len(rivers)} |\n")
    lines.append(f"## Rivers ({len(rivers)})\n")
    lines.append(" · ".join(rivers) + "\n")
    lines.append(f"## Lakes ({len(lakes)})\n")
    lines.append(" · ".join(lakes) + "\n")
    lines.append(f"## Passes ({len(passes)}) — highest first\n")
    lines.append("| Pass | m | ft |")
    lines.append("|---|--:|--:|")
    lines += elev_rows(passes)
    lines.append("")
    lines.append(f"## Peaks ({len(peaks)}) — highest first\n")
    lines.append("| Peak | m | ft |")
    lines.append("|---|--:|--:|")
    lines += elev_rows(peaks)
    lines.append("")
    open(os.path.join(REPO, "TOPO_SUMMARY.md"), "w").write("\n".join(lines))
    print("  wrote TOPO_SUMMARY.md")


def main():
    b = load_bbox()
    write_trails(b)
    write_topo(b)


if __name__ == "__main__":
    main()
